name: OIDC Authentication Test

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  oidc-auth:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::419676625339:role/githubaction-OIDC-Gnosisconnect-iac-role
          aws-region: us-east-1

      - name: Verify AWS Identity
        run: aws sts get-caller-identity